use LWP::UserAgent;
use HTTP::Request::Common qw(GET);
use JSON;

my $ua = LWP::UserAgent->new;
my $url = "https://lmc.isb.cn/api/v1/rest/context/destiny/";  # Replace with your desired endpoint

# Set up the GET request with the access token in the header
my $request = GET $url;
$request->header("Authorization" => "Bearer eyJhbGciOiJSUzI1NiJ9.eyJhenAiOiJkZXN0aW55OmFwaWtleTpvWkhKU2FNdC52MHZWLlFjOTg3MWJvblRsZHpleV83PSIsImF1ZCI6ImRlc3RpbnktRkM0NC1TM0ZXIiwicHJpbmNpcGFsR3JhbnRzIjoiRmluZXNBZGRBc3NldCxGaW5lc0FkZExpYnJhcnksRmluZXNBZGRQYXRyb24sRmluZXNBZGRUZXh0Ym9vayxGaW5lc0RlbGV0ZUFzc2V0LEZpbmVzRGVsZXRlTGlicmFyeSxGaW5lc0RlbGV0ZVBhdHJvbixGaW5lc0RlbGV0ZVRleHRib29rLEZpbmVzUGF5QXNzZXQsRmluZXNQYXlMaWJyYXJ5LEZpbmVzUGF5UGF0cm9uLEZpbmVzUGF5VGV4dGJvb2ssVmlld0ZpbmVzQXNzZXQsVmlld0FueUZpbmVzLFZpZXdGaW5lc1BhdHJvbixWaWV3RmluZXNUZXh0Ym9vayxGaW5lc1dhaXZlQXNzZXQsRmluZXNXYWl2ZUxpYnJhcnksRmluZXNXYWl2ZVBhdHJvbixGaW5lc1dhaXZlVGV4dGJvb2ssQ2F0QXNzZXRTZWFyY2hBc3NldHMsQ2F0QXNzZXRTZWFyY2hBbGxBc3NldFNpdGVzLENhdEFzc2V0QWRkQXNzZXRTcGVjLENhdEFzc2V0RWRpdEFzc2V0U3BlYyxDYXRBc3NldEFkZEFzc2V0LENhdEFzc2V0RWRpdEFzc2V0LENhdEFzc2V0RGVsZXRlQXNzZXQsTWFya0Fzc2V0TG9zdCxBcHByb3ZlQXNzZXREaXNwb3NhbCxCYXNpY1NlYXJjaCxBZHZhbmNlZFNlYXJjaCxRdWVzdFNlYXJjaCxVRFNlYXJjaCxWaXN1YWxTZWFyY2gsTnVtYmVyU2VhcmNoLENhdGVnb3J5U2VhcmNoLENhbGxOdW1iZXJTZWFyY2gsQmFyY29kZVNlYXJjaCxCcmllZlNlYXJjaCxQbGFjZUhvbGRGb3JTZWxmLFBsYWNlSG9sZEZvckF2YWlsYWJsZUNvcGllcyxEZWxldGVIb2xkRm9yU2VsZixQbGFjZUlMTEZvclNlbGYsSG9sZE11bHRpcGxlQ29waWVzRm9yU2VsZixTaG93SGlkZGVuTWF0ZXJpYWxzLFNlYXJjaFBhdHJvbnNBY3Jvc3NEaXN0cmljdCxQYXRyb25TdGF0dXNWaWV3QXNzZXRJdGVtc091dCxQYXRyb25TdGF0dXNWaWV3TGlicmFyeUl0ZW1zT3V0LFZpZXdQYXRyb25TdGF0dXMsVmlld093blN0YXR1cyxBRURIb2xkcyxBZGRUaXRsZXMsQWRkVGl0bGVzRHVyaW5nQ2hlY2tvdXQiLCJzZXJ2aWNlVHlwZSI6IkRFU1RJTlkiLCJleHBpcnkiOiIyMDI0LTExLTA1VDA0OjA0OjQzLjI2MVoiLCJpYXQiOjE3MzA3NzU4ODMsImV4cCI6MTczMDc3OTQ4M30.rmUjolxpfbF6xC2kGWP3wxDJAdm8VrQaAceHWAaoedVorJ1N9QjHnSOhaVZNBxXxI3jT6A6wtz8FmxKK-tIxZki9ua54m-zGpXjDEyh4m-sQuARu1N_thVqIYPdlihMQ7Mhq16-Te3yyxn6jdyY3Vs6A9Qo-fO6qt5ndEZuABuPQTnWLUuM56K6ol-LdBiFdxwMdbBCD8DywL2Onw139dwx0SBw-iDswb8YPHUjtL5FWjnTJUglREzIpj-dT8OEHwyiI9a0o-EIXIHUdd9s2GrRYsmlNirrmhkP814Hrm2N-U-uV0L_abY94NXXtajAvveACcY8hErWRc7jwqdVFZQ");  # Replace with your actual token

my $response = $ua->request($request);

if ($response->is_success) {
    my $data = decode_json($response->decoded_content);
    print "Response Data: ", $data, "\n";
} else {
    print "Failed to fetch data: ", $response->status_line, "\n";
}
